
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 10 04:58:28 COT 2022
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Extern = 12;
  public static final int Op_decremento = 65;
  public static final int Parentesis_c = 69;
  public static final int Return = 13;
  public static final int Parentesis_a = 68;
  public static final int Llave_c = 71;
  public static final int Op_smaller_than = 50;
  public static final int Llave_a = 70;
  public static final int Std = 81;
  public static final int Op_desplazamiento_bits_izq = 63;
  public static final int Coma = 88;
  public static final int Linea = 2;
  public static final int Break = 38;
  public static final int Corchete_c = 73;
  public static final int Corchete_a = 72;
  public static final int Long = 25;
  public static final int Punto = 87;
  public static final int Default = 37;
  public static final int Punto_coma = 90;
  public static final int Char = 28;
  public static final int For = 34;
  public static final int Void = 15;
  public static final int Op_greater_than_equal_to = 53;
  public static final int Op_modulo = 61;
  public static final int Else = 31;
  public static final int Resta = 40;
  public static final int Op_and = 45;
  public static final int Int = 23;
  public static final int SystemC = 19;
  public static final int Cin = 83;
  public static final int Using = 79;
  public static final int Suma = 39;
  public static final int ERROR = 95;
  public static final int Op_asignacion = 56;
  public static final int Cadena = 29;
  public static final int Typedef = 17;
  public static final int Main = 85;
  public static final int Op_and_b2b = 47;
  public static final int Op_true = 66;
  public static final int Do = 32;
  public static final int Static = 14;
  public static final int Op_or = 44;
  public static final int Signed = 20;
  public static final int Unsigned = 10;
  public static final int Op_false = 67;
  public static final int Short = 24;
  public static final int Case = 36;
  public static final int Volatile = 18;
  public static final int Const = 5;
  public static final int Endl = 84;
  public static final int Continue = 11;
  public static final int Op_suma = 57;
  public static final int Byte = 22;
  public static final int Op_not = 49;
  public static final int Math = 74;
  public static final int Sizeof = 8;
  public static final int Op_desplazamiento_bits_der = 62;
  public static final int Auto = 4;
  public static final int If = 30;
  public static final int Stdio = 75;
  public static final int EOF = 0;
  public static final int Op_division = 60;
  public static final int Cout = 82;
  public static final int Op_equal = 54;
  public static final int Numero = 94;
  public static final int Time = 77;
  public static final int Double = 27;
  public static final int Struct = 16;
  public static final int Division = 42;
  public static final int Almohadilla = 91;
  public static final int Stdlib = 76;
  public static final int Op_not_equal = 55;
  public static final int Dos_puntos = 89;
  public static final int Namespace = 80;
  public static final int error = 1;
  public static final int Op_smaller_than_equal_to = 51;
  public static final int Op_greater_than = 52;
  public static final int Op_multiplicacion = 59;
  public static final int Comillas = 3;
  public static final int Enum = 6;
  public static final int Float = 26;
  public static final int Op_xor_b2b = 48;
  public static final int Identificador = 93;
  public static final int Iostream = 78;
  public static final int Op_incremento = 64;
  public static final int Include = 92;
  public static final int Modulo = 43;
  public static final int Printf = 86;
  public static final int Op_or_b2b = 46;
  public static final int Register = 9;
  public static final int Op_resta = 58;
  public static final int Goto = 7;
  public static final int While = 33;
  public static final int Union = 21;
  public static final int Multiplicacion = 41;
  public static final int Switch = 35;
}

