
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 29 07:59:38 COT 2022
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Return = 27;
  public static final int Op_atr_incremento = 71;
  public static final int Llave_c = 21;
  public static final int Llave_a = 20;
  public static final int Std = 45;
  public static final int Coma = 76;
  public static final int Linea = 10;
  public static final int Break = 34;
  public static final int Parent_c = 19;
  public static final int Parent_a = 18;
  public static final int Corchete_c = 23;
  public static final int True = 73;
  public static final int Corchete_a = 22;
  public static final int Long = 8;
  public static final int Punto = 77;
  public static final int Default = 35;
  public static final int Char = 3;
  public static final int Op_atr_decremento = 72;
  public static final int For = 39;
  public static final int Void = 33;
  public static final int Op_rel_diferente = 60;
  public static final int Else = 26;
  public static final int Op_rel_menor_que = 58;
  public static final int Resta = 14;
  public static final int Int = 2;
  public static final int Op_rel_desplaz_izq = 63;
  public static final int Cin = 46;
  public static final int Suma = 13;
  public static final int Using = 42;
  public static final int Op_atr_division = 69;
  public static final int ERROR = 81;
  public static final int Cadena = 7;
  public static final int Op_log_or = 53;
  public static final int Typedef = 31;
  public static final int Op_log_and = 52;
  public static final int Main = 51;
  public static final int Do = 36;
  public static final int Op_rel_mayor_que = 57;
  public static final int P_coma = 75;
  public static final int Unsigned = 43;
  public static final int Short = 9;
  public static final int Op_atr_producto = 68;
  public static final int Scanf = 49;
  public static final int Case = 32;
  public static final int Op_rel_equivalente = 59;
  public static final int Const = 28;
  public static final int Continue = 29;
  public static final int Byte = 4;
  public static final int Op_atr_suma = 65;
  public static final int Op_inclu_lib = 67;
  public static final int Op_atr_resta = 66;
  public static final int If = 24;
  public static final int Define = 47;
  public static final int EOF = 0;
  public static final int Cout = 48;
  public static final int Op_log_not = 54;
  public static final int Numero = 80;
  public static final int Double = 5;
  public static final int Struct = 38;
  public static final int Division = 16;
  public static final int Op_rel_mayor_igual = 61;
  public static final int Dos_puntos = 78;
  public static final int Op_log_and_bit = 55;
  public static final int Namespace = 44;
  public static final int error = 1;
  public static final int False = 74;
  public static final int Op_atr_modulo = 70;
  public static final int Op_rel_menor_igual = 62;
  public static final int Comillas = 11;
  public static final int Float = 6;
  public static final int Op_log_or_bit = 56;
  public static final int Op_rel_desplaz_der = 64;
  public static final int Identificador = 79;
  public static final int Iostream = 41;
  public static final int Include = 40;
  public static final int Modulo = 17;
  public static final int Printf = 50;
  public static final int Register = 25;
  public static final int Igual = 12;
  public static final int While = 37;
  public static final int Multiplicacion = 15;
  public static final int Switch = 30;
}

